### ISSUE TITLE
Driver build issue

### ISSUE THREAD

**Issue by kirilsagoth** [ibm-security-intelligence/jdbc-driver#3]
Hello, 
I have been trying to generate jdbc driver for the purpose of data extraction from the QR Ariel DB.

I followed the instructions in the description, 
[myLog.txt](https://github.com/ibm-security-intelligence/jdbc-driver/files/407030/myLog.txt)

The regular build (with all the tests) failed [log is attached]
then I tried building without the tests using:   _mvn -Dmaven.test.skip=true clean package_
the testless build was successful and both .jar files were created, however when I tried using 
jaql-0.2-jar-with-dependencies.jar
I got:
Caused by: java.lang.NullPointerException
    at com.ibm.si.jaql.rest.ArielDatabase.loadColumnMetaData(ArielDatabase.java:130)
    at com.ibm.si.jaql.rest.ArielDatabase.<init>(ArielDatabase.java:62)
    at com.ibm.si.jaql.api.ArielFactory.getArielDatabase(ArielFactory.java:31)
    at com.ibm.si.jaql.jdbc4.QueryExecutor.<init>(QueryExecutor.java:34)
    ... 7 more

When I dug a bit in the drivers source I saw that one dependency is missing: com.ibm.si.jaql.aql.StatementParser

I cant locate this dependency and it seems like the cause of the exceptions (of course I might be wrong about this)

Would much appreciate your kind advice on how to resolve this issue.
Thank you.

**Comment by kirilsagoth** [comment]
[myLog.txt](https://github.com/ibm-security-intelligence/jdbc-driver/files/407033/myLog.txt)

**Comment by woshiwuja** [comment]
any news? im trying to access the ariel database without having to use the REST API, having a similar problem, is there any way i can build the driver without SSL verification?
