### ISSUE TITLE
Driver SSL connection issue

### ISSUE THREAD

**Issue by leejian0612** [ibm-security-intelligence/jdbc-driver#5]
HI,    
I am trying to use this driver to connect to a qradar console, which using a cert authorized by a public CA,  but I get errors like below,
```
Begin to get the ssl connection
java.sql.SQLException: Could not obtain ariel connection
	at com.ibm.si.jaql.jdbc4.QueryExecutor.<init>(QueryExecutor.java:44)
	at com.ibm.si.jaql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:39)
	at com.ibm.si.jaql.Driver.connect(Driver.java:95)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at QradarSSLConnection.getConnection(QradarSSLConnection.java:17)
	at QradarSSLConnection.main(QradarSSLConnection.java:36)
Caused by: com.ibm.si.jaql.api.ArielException: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at com.ibm.si.jaql.rest.RESTClient.<init>(RESTClient.java:107)
	at com.ibm.si.jaql.rest.ArielDatabase.<init>(ArielDatabase.java:54)
	at com.ibm.si.jaql.api.ArielFactory.getArielDatabase(ArielFactory.java:31)
	at com.ibm.si.jaql.jdbc4.QueryExecutor.<init>(QueryExecutor.java:34)
	... 6 more
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.ibm.si.jaql.rest.RESTClient.<init>(RESTClient.java:98)
	... 9 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
	at org.apache.http.conn.ssl.SSLContextBuilder$TrustManagerDelegate.checkServerTrusted(SSLContextBuilder.java:190)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:984)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 22 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 36 more
```

**Comment by leejian0612** [comment]
And this is my code 
```
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;

public class QradarSSLConnection
{
private static String url = "jdbc:qradar://URL/";
private static String username = "admin";
private static String password = "PASSWORD";
public static Connection getConnection()
{
	Connection conn=null;
	try
	{
		Class.forName("com.ibm.si.jaql.Driver");
		conn=DriverManager.getConnection(url,username,password);
	}
	catch(SQLException e)
	{
		e.printStackTrace();
	}
	catch(ClassNotFoundException e)
	{
		System.out.println("exception2:"+e);
	}
	return conn;
	}
`
public static void main( String[] args )
{
	System.out.println("Begin to get the ssl connection");
	System.setProperty("jsse.enableSNIExtension", "false");
	//System.setProperty("javax.net.ssl.trustStore", "/Users/cacerts");
        //System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
	QradarSSLConnection.getConnection();
	System.out.println("End to get the ssl connection ");
}
}
```

Any idea for this ssl issue? and how to set the truststore for this jdbc-driver? Does it related to qradarstore?

**Comment by JasonKeirstead** [comment]
Please see here to see how to configure QRadar to trust a SSL certificate

https://www.ibm.com/support/knowledgecenter/SSKMKU/com.ibm.qradar.doc/t_qradar_adm_conf_ssl_tls_cert.html

**Comment by leejian0612** [comment]
@JasonKeirstead 
Thanks for your quick reply.
But I think the problem is occurred on the client side, not the qradar server side, when the rest client init, it will execute 
```
res = client.execute(targetHost, wakeUp, context);
```
and then raise an "ArielException", which is caused by 
```
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
so I think we need add the server cert to client keystores, I have try to add it to 
```
/qradarstore
/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/security/cacerts
``` 
but it not work.

or if you think I need to add some certs to qradar console, can your explain it in details? because the client seems do not has its cert...
 
I have been stroked by this problems for several days, and really need some guidance.
Thanks again

**Comment by leejian0612** [comment]
@JasonKeirstead
I think I find the root casue.
In defaut, this driver can connect to a self signed console,
```
final SSLContext sslContext = SSLContexts.custom()
                                        .loadTrustMaterial(trustStore, new TrustSelfSignedStrategy())
					.build();
``` 
but when the console is not self signed, it will get the trust certs from the trustStore
```
private final String QRADARSTORE_RESOURCE_NAME = "/qradarstore";
final KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());			
final InputStream inStream = RESTClient.class.getResourceAsStream(QRADARSTORE_RESOURCE_NAME);
trustStore.load(inStream, "devtest".toCharArray());
``` 
pay attention here, the trustStore is got through  ```RESTClient.class.getResourceAsStream``` , and start with ```/```, so it should be located at the classpath directory or in the jar.

Below is my solution,
1. Get the original truststore from ```https://github.com/ibm-security-intelligence/jdbc-driver/blob/master/src/main/resources/qradarstore```, and its password should be ```devtest```, then add the trust chain for your console to it.            
2. Add the  qradarstore to the jaql-0.2-jar-with-dependencies.jar
 **zip jaql-0.2-jar-with-dependencies.jar qradarstore**

I think we should improve the method to get the truststore,  it should be configurable or we can just use the default JVM truststore, not hard coded.
